# Configuración de la base de datos PostgreSQL
spring.datasource.url=${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
